"""add_meltdowns_and_reminders

Revision ID: 9b40a9a90334
Revises: a0108c504054
Create Date: 2026-09-11 00:12:09.604834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b40a9a90334'
down_revision: Union[str, Sequence[str], None] = 'a0108c504054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meltdown_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meltdown_incidents_child_id'), 'meltdown_incidents', ['child_id'], unique=False)
    op.create_index(op.f('ix_meltdown_incidents_id'), 'meltdown_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_meltdown_incidents_start_time'), 'meltdown_incidents', ['start_time'], unique=False)
    op.create_table('reminder_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_notifications_child_id'), 'reminder_notifications', ['child_id'], unique=False)
    op.create_index(op.f('ix_reminder_notifications_id'), 'reminder_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_notifications_user_id'), 'reminder_notifications', ['user_id'], unique=False)
    op.create_table('meltdown_strategies_applied',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meltdown_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_category', sa.String(length=50), nullable=False),
    sa.Column('efficacy', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['meltdown_id'], ['meltdown_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meltdown_strategies_applied_id'), 'meltdown_strategies_applied', ['id'], unique=False)
    op.create_index(op.f('ix_meltdown_strategies_applied_meltdown_id'), 'meltdown_strategies_applied', ['meltdown_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meltdown_strategies_applied_meltdown_id'), table_name='meltdown_strategies_applied')
    op.drop_index(op.f('ix_meltdown_strategies_applied_id'), table_name='meltdown_strategies_applied')
    op.drop_table('meltdown_strategies_applied')
    op.drop_index(op.f('ix_reminder_notifications_user_id'), table_name='reminder_notifications')
    op.drop_index(op.f('ix_reminder_notifications_id'), table_name='reminder_notifications')
    op.drop_index(op.f('ix_reminder_notifications_child_id'), table_name='reminder_notifications')
    op.drop_table('reminder_notifications')
    op.drop_index(op.f('ix_meltdown_incidents_start_time'), table_name='meltdown_incidents')
    op.drop_index(op.f('ix_meltdown_incidents_id'), table_name='meltdown_incidents')
    op.drop_index(op.f('ix_meltdown_incidents_child_id'), table_name='meltdown_incidents')
    op.drop_table('meltdown_incidents')
    # ### end Alembic commands ###
