"""Add visual_schedules, schedule_tasks, task_completions

Revision ID: a0108c504054
Revises: 5527db5388e3
Create Date: 2026-09-10 12:25:00.723543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0108c504054'
down_revision: Union[str, Sequence[str], None] = '5527db5388e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_schedules_child_id'), 'visual_schedules', ['child_id'], unique=False)
    op.create_index(op.f('ix_visual_schedules_id'), 'visual_schedules', ['id'], unique=False)
    op.create_table('schedule_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('icon_key', sa.String(length=50), nullable=False),
    sa.Column('audio_prompt_url', sa.String(length=255), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['visual_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_tasks_id'), 'schedule_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_tasks_schedule_id'), 'schedule_tasks', ['schedule_id'], unique=False)
    op.create_table('task_completions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['schedule_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completions_completion_date'), 'task_completions', ['completion_date'], unique=False)
    op.create_index(op.f('ix_task_completions_id'), 'task_completions', ['id'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_completion_date'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index(op.f('ix_schedule_tasks_schedule_id'), table_name='schedule_tasks')
    op.drop_index(op.f('ix_schedule_tasks_id'), table_name='schedule_tasks')
    op.drop_table('schedule_tasks')
    op.drop_index(op.f('ix_visual_schedules_id'), table_name='visual_schedules')
    op.drop_index(op.f('ix_visual_schedules_child_id'), table_name='visual_schedules')
    op.drop_table('visual_schedules')
    # ### end Alembic commands ###
