"""add_clinician_portal_and_notes

Revision ID: bd562ff6c33f
Revises: 9b40a9a90334
Create Date: 2026-09-11 01:01:00.857899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd562ff6c33f'
down_revision: Union[str, Sequence[str], None] = '9b40a9a90334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_child_id'), 'clinical_notes', ['child_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_clinician_id'), 'clinical_notes', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_id'), 'clinical_notes', ['id'], unique=False)
    op.create_table('clinician_patient_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_patient_assignments_child_id'), 'clinician_patient_assignments', ['child_id'], unique=False)
    op.create_index(op.f('ix_clinician_patient_assignments_clinician_id'), 'clinician_patient_assignments', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_clinician_patient_assignments_id'), 'clinician_patient_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinician_patient_assignments_id'), table_name='clinician_patient_assignments')
    op.drop_index(op.f('ix_clinician_patient_assignments_clinician_id'), table_name='clinician_patient_assignments')
    op.drop_index(op.f('ix_clinician_patient_assignments_child_id'), table_name='clinician_patient_assignments')
    op.drop_table('clinician_patient_assignments')
    op.drop_index(op.f('ix_clinical_notes_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_clinician_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_child_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    # ### end Alembic commands ###
